language: node_js
node_js: 10
matrix:
    include:
        - os: linux
          dist: trusty
        - os: osx
          osx_image: xcode8.3
addons:
  sonarcloud:
    organization: "onest-io"
    token:
      secure: "836a8d667feefee0411e32013bfb4f943927a533" # encrypted value of your token
