language: node_js
node_js: 10
matrix:
    include:
        - os: linux
          dist: trusty
        - os: osx
          osx_image: xcode8.3
addons:
  sonarcloud:
    organization: "onest-io"
    token:
      secure: "travis encrypt e6fc36fc864cbbd37283bec30e5a52248ebb82ec" # encrypted value of your token
